name = "pkmntcg-deals-api"
main = "index.js"
compatibility_date = "2024-06-10"
# Service Worker (classic) compatible

[[kv_namespaces]]
binding = "POSTS"
id = "f7407063c957413cae56087eac76aff3"

[[kv_namespaces]]
binding = "FEED"
id = "98c9e9ac048a472dbae0aa23abbf7742"
